# Generated by Django 5.1.1 on 2024-09-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('from_currency', models.CharField(max_length=4)),
                ('to_currency', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversion_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
